### ISSUE TITLE
IPython console fails to load in QGIS 3

### ISSUE THREAD

**Issue by Zeitsperre** [elpaso/qgis-ipythonconsole#19]
I haven't had much luck getting the IPython console to load in dock or windowed form. I'm wondering if there could be unlisted dependencies that the plugin requires or if it's something on my end. Stack trace as follows:

```
2018-04-06T09:34:17	WARNING	Traceback (most recent call last):
			  File "/home/tjs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/IPyConsole/IPyConsole.py", line 158, in docked
			    self.run(dock=True)
			  File "/home/tjs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/IPyConsole/IPyConsole.py", line 249, in run
			    from qtconsole.rich_ipython_widget import RichIPythonWidget
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/qtconsole/rich_ipython_widget.py", line 3, in <module>
			    from .rich_jupyter_widget import *
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
			    from .jupyter_widget import JupyterWidget
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 19, in <module>
			    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
			    from .terminal.embed import embed
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/IPython/terminal/embed.py", line 15, in <module>
			    from IPython.core.interactiveshell import DummyMod, InteractiveShell
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 90, in <module>
			    import docrepr.sphinxify as sphx
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/docrepr/sphinxify.py", line 34, in <module>
			    from sphinx.application import Sphinx
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 30, in <module>
			    from sphinx.config import Config
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/sphinx/config.py", line 21, in <module>
			    from sphinx.util.i18n import format_date
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/sphinx/util/i18n.py", line 19, in <module>
			    import babel.dates
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/babel/dates.py", line 29, in <module>
			    from babel.util import UTC, LOCALTZ
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/babel/util.py", line 19, in <module>
			    from babel import localtime
			  File "/usr/share/qgis/python/qgis/utils.py", line 664, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/lib/python3.6/site-packages/babel/localtime/__init__.py", line 74, in <module>
			    LOCALTZ = get_localzone()
			  File "/usr/lib/python3.6/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
			    return _get_localzone()
			  File "/usr/lib/python3.6/site-packages/babel/localtime/_unix.py", line 57, in _get_localzone
			    return pytz.timezone(zone_name)
			  File "/usr/lib/python3.6/site-packages/pytz/__init__.py", line 155, in timezone
			    zone = _unmunge_zone(zone)
			  File "/usr/lib/python3.6/site-packages/pytz/__init__.py", line 171, in _unmunge_zone
			    return zone.replace('_plus_', '+').replace('_minus_', '-')
			TypeError: a bytes-like object is required, not 'str''
```

I'm currently running this on a fresh openSUSE Tumbleweed vm with IPython2/3 installed.

**Comment by elpaso** [comment]
Looks more like an error in pytz https://bugs.launchpad.net/pytz/+bug/1606694
