### ISSUE TITLE
Installing IPython on a PC with QGIS 2 and QGIS 3 (OSGeo4W)

### ISSUE THREAD

**Issue by mstuyts** [elpaso/qgis-ipythonconsole#26]
I installed the plugin in QGIS 3.4.4 on a PC (Win10) that also has QGIS 2.18.28 installed (both installed with OSGeo4W).  After I installed IPython using `pip install jupyter==1.0.0 qtconsole` in the OSGeo4W shell, the plugin doesn't recognize the IPython installation. I noticed QGIS 3.4.4 and the OSGeo4W shell use a different Python version: QGIS uses Python 3 and OSGeo4W shell uses Python 2.7 by default. So  pip installs IPython in the wrong location for use in QGIS 3.4.4.

If I first run `py3_env` in the OSGeo4W shell and after that install IPython with `pip3 install jupyter==1.0.0 qtconsole` the plugin recognizes the IPython installation.  

After installing IPython to the correct location, the IPython console can be used in QGIS 3.4.4, but opening the IPython console window gives the following error: ` AttributeError: module 'IPython.core.usage' has no attribute 'default_gui_banner'`, but that probably is the same as issue #22.

**Comment by elpaso** [comment]
I've just uploaded a few changes, would you able to test them? 
https://github.com/elpaso/qgis-ipythonconsole/archive/master.zip

**Comment by mstuyts** [comment]
With this new version I get the following error when I try to open the IPython console:

**ValueError: fallback required, but not specified** 
```
Traceback (most recent call last):
  File "C:/Users/michstuy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\IPyConsole\IPyConsole.py", line 198, in default
    self.run(dock=(self.get_settings('default_window_mode', DEFAULT_WINDOW_MODE) == 'docked'))
  File "C:/Users/michstuy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\IPyConsole\IPyConsole.py", line 303, in run
    kernel_manager.start_kernel()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\ipykernel\inprocess\manager.py", line 46, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 72, in __init__
    super(InProcessKernel, self).__init__(**traits)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\ipykernel\ipkernel.py", line 67, in __init__
    kernel      = self,
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 672, in __init__
    self.init_io()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 837, in init_io
    io.stdout = io.IOStream(sys.stdout)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\IPython\utils\io.py", line 31, in __init__
    raise ValueError("fallback required, but not specified")
ValueError: fallback required, but not specified
```

**Comment by joshwarren** [comment]
Have had the same error. There is also a Deprecation Warning that IPython.qt was deprecated in IPython 4.0. It is imported in line 253 of IPyConsole.py

```
traceback: File "C:/Users/jwarren/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\IPyConsole\IPyConsole.py", line 153, in default
self.run(dock=(self.get_settings('default_window_mode', DEFAULT_WINDOW_MODE) == 'docked'))
File "C:/Users/jwarren/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\IPyConsole\IPyConsole.py", line 253, in run
from IPython.qt.inprocess import QtInProcessKernelManager
File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "", line 983, in _find_and_load
File "", line 953, in _find_and_load_unlocked
File "", line 219, in _call_with_frames_removed
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "C:\Users\jwarren\AppData\Roaming\Python\Python37\site-packages\IPython\qt.py", line 13, in 
"You should import from qtconsole instead.", ShimWarning)
```
